### ISSUE TITLE
[Feature Request] Provide arm32/v7 (Raspberry PI) docker image

### ISSUE THREAD

**Issue by jk** [bluewalk/NukiBridge2Mqtt#28]
Hi,

I've read your posts over there at the Nuki forum in [this thread](https://developer.nuki.io/t/mqtt-support/898/5). I want to run your docker image on my Raspberry Pi 4. But hadn't had any luck with the image you published on Docker hub nor compiling an mulit-arch image myself via 
```bash
docker buildx create --use --name build --node build --driver-opt network=host
docker buildx build --push --platform linux/arm/v7,linux/amd64 --tag jkohl/nukibridge2mqtt:latest .
```

The log shows the following:
```
[+] Building 253.5s (18/27)
 => [internal] load .dockerignore                                                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                                                 0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                            0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                             0.0s
 => [linux/amd64 internal] load metadata for mcr.microsoft.com/dotnet/core/runtime:2.2-alpine3.9                                                                                                                0.2s
 => [linux/amd64 internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:2.2                                                                                                                              0.2s
 => [linux/arm/v7 internal] load metadata for mcr.microsoft.com/dotnet/core/runtime:2.2-alpine3.9                                                                                                               0.2s
 => [linux/arm/v7 internal] load metadata for mcr.microsoft.com/dotnet/core/sdk:2.2                                                                                                                             0.2s
 => [linux/amd64 build 1/4] FROM mcr.microsoft.com/dotnet/core/sdk:2.2@sha256:42699bba2fe4545dd753694499e6db08478ba5b3bcc34b929e7e324d4c115449                                                                249.0s
 => => resolve mcr.microsoft.com/dotnet/core/sdk:2.2@sha256:42699bba2fe4545dd753694499e6db08478ba5b3bcc34b929e7e324d4c115449                                                                                    0.0s
 => => sha256:e705a4c4fd310b96bfb3d7928428e65f0d3f5bad0cd0bda1434aee1d89418468 50.07MB / 50.07MB                                                                                                               88.1s
 => => sha256:db9b38d066fdbdd5ac5ce862076c27e4ae17f2b57cbacd03bdc3b24e06696ae8 1.80kB / 1.80kB                                                                                                                  0.0s
 => => sha256:ff05a093e8aa7f92b287883ed215c63b767074e67aa2a730ae82fd8ed6e1bd89 301.07MB / 301.07MB                                                                                                            221.5s
 => => sha256:2357b6790b9df0fb28364d113ff94eb67628cb1564aa86074d24c68b1597b62e 4.40kB / 4.40kB                                                                                                                  0.0s
 => => sha256:146bd6a886182fde06fbf747470b1c89814bc8ab1c96fdf1aef6107171959fe6 45.38MB / 45.38MB                                                                                                               87.9s
 => => sha256:563ac9aa7c8039c3169f383c57e43c0d8281d01f6b6c59a4f5b0e9168a9a3427 13.25MB / 13.25MB                                                                                                               40.0s
 => => sha256:42699bba2fe4545dd753694499e6db08478ba5b3bcc34b929e7e324d4c115449 2.19kB / 2.19kB                                                                                                                  0.0s
 => => sha256:db0efb86e80601b5bbdbb7c406426982c4202d339687c14c3941b364527e2249 4.34MB / 4.34MB                                                                                                                 12.8s
 => => sha256:9935d0c62ace92b388be202275e222007d6cac10b9c1f2c1ea63af38c09ea7ab 10.80MB / 10.80MB                                                                                                               33.1s
 => => sha256:9db5b5c16f62413ee33c1b77d00b801b18b0a9bb8dd5151c35cad7a757d4e33f 173.40MB / 173.40MB                                                                                                            201.5s
 => => unpacking mcr.microsoft.com/dotnet/core/sdk:2.2@sha256:42699bba2fe4545dd753694499e6db08478ba5b3bcc34b929e7e324d4c115449                                                                                 27.4s
 => [internal] load build context                                                                                                                                                                               0.0s
 => => transferring context: 5.91kB                                                                                                                                                                             0.0s
 => [linux/amd64 runtime 1/3] FROM mcr.microsoft.com/dotnet/core/runtime:2.2-alpine3.9@sha256:ebe69f80d710d6f54f798f64de82b72ef2f95a38608e5b3cb5b8b2d41b017a5f                                                 78.7s
 => => resolve mcr.microsoft.com/dotnet/core/runtime:2.2-alpine3.9@sha256:ebe69f80d710d6f54f798f64de82b72ef2f95a38608e5b3cb5b8b2d41b017a5f                                                                      0.0s
 => => sha256:ebe69f80d710d6f54f798f64de82b72ef2f95a38608e5b3cb5b8b2d41b017a5f 951B / 951B                                                                                                                      0.0s
 => => sha256:3a1d61088def3f2b3b8b3eeb96803aed795e2202d20c75bf5a4fd81bb2c12be4 29.80MB / 29.80MB                                                                                                               76.8s
 => => sha256:564715af7ab8472459a377c3062e324b1a718c1c8e01a02e62be275397e26deb 2.33MB / 2.33MB                                                                                                                  6.7s
 => => sha256:e7c96db7181be991f19a9fb6975cdbbd73c65f4a2681348e63a141a2192a5f10 2.76MB / 2.76MB                                                                                                                  7.6s
 => => sha256:8820c012d899dd48aa5a48462869b869053d41208cf7f224728fb139faeee96a 3.69kB / 3.69kB                                                                                                                  0.0s
 => => unpacking mcr.microsoft.com/dotnet/core/runtime:2.2-alpine3.9@sha256:ebe69f80d710d6f54f798f64de82b72ef2f95a38608e5b3cb5b8b2d41b017a5f                                                                    1.8s
 => [linux/arm/v7 build 1/4] FROM mcr.microsoft.com/dotnet/core/sdk:2.2@sha256:42699bba2fe4545dd753694499e6db08478ba5b3bcc34b929e7e324d4c115449                                                               245.6s
 => => resolve mcr.microsoft.com/dotnet/core/sdk:2.2@sha256:42699bba2fe4545dd753694499e6db08478ba5b3bcc34b929e7e324d4c115449                                                                                    0.0s
 => => sha256:061c84a1042c4c22155421a671bec39485c59cd86e8d81f00ab69d6e9c2e7699 1.80kB / 1.80kB                                                                                                                  0.0s
 => => sha256:d2f5b057e8bf968e461d38731812e42e9244509ef7b62e6a4eac9c7d5e065d40 301.07MB / 301.07MB                                                                                                            220.6s
 => => sha256:b7dff6eadd6f1c5f6590cf6460cffbc004373ede7e9fdc0ff9d28f30a4818715 4.90kB / 4.90kB                                                                                                                  0.0s
 => => sha256:b531ae4a39253d883a11291e842b7e1aa9dae38f9d9b77ddea55b2625ce986e3 42.11MB / 42.11MB                                                                                                               98.6s
 => => sha256:42699bba2fe4545dd753694499e6db08478ba5b3bcc34b929e7e324d4c115449 2.19kB / 2.19kB                                                                                                                  0.0s
 => => sha256:f2acc26f3a3d327e31fa0c52ccf0fc43a9e7fc678104a47173e6e43557874d6f 13.04MB / 13.04MB                                                                                                               36.3s
 => => sha256:22754f6fc5d5a244119c0928ebf7d851d276d7f095f07e6bf435fa7afbcab8a8 9.50MB / 9.50MB                                                                                                                 41.6s
 => => sha256:fad0ae2287846b9d91f237a798b6ae550ff58e33efb804be1ca049f9fd7a480f 46.40MB / 46.40MB                                                                                                               70.2s
 => => sha256:580c7908dce0bb1f289e99f7a7426f0607a353d3d485f9302811d2ace7c8f044 144.44MB / 144.44MB                                                                                                            175.0s
 => => sha256:cb2155e4b3456accbea4b6873247312dd288feb477ec966ed48637e031aba558 3.92MB / 3.92MB                                                                                                                 11.6s
 => => unpacking mcr.microsoft.com/dotnet/core/sdk:2.2@sha256:42699bba2fe4545dd753694499e6db08478ba5b3bcc34b929e7e324d4c115449                                                                                 24.8s
 => [linux/arm/v7 runtime 1/3] FROM mcr.microsoft.com/dotnet/core/runtime:2.2-alpine3.9@sha256:ebe69f80d710d6f54f798f64de82b72ef2f95a38608e5b3cb5b8b2d41b017a5f                                                 0.0s
 => => resolve mcr.microsoft.com/dotnet/core/runtime:2.2-alpine3.9@sha256:ebe69f80d710d6f54f798f64de82b72ef2f95a38608e5b3cb5b8b2d41b017a5f                                                                      0.0s
 => [linux/amd64 runtime 2/3] WORKDIR /app                                                                                                                                                                      0.0s
 => [linux/arm/v7 build 2/4] WORKDIR /app                                                                                                                                                                       0.2s
 => [linux/arm/v7 build 3/4] COPY . ./                                                                                                                                                                          0.1s
 => ERROR [linux/arm/v7 build 4/4] RUN dotnet restore                                                                                                                                                           7.2s
 => [linux/amd64 build 2/4] WORKDIR /app                                                                                                                                                                        0.2s
 => [linux/amd64 build 3/4] COPY . ./                                                                                                                                                                           0.1s
 => CANCELED [linux/amd64 build 4/4] RUN dotnet restore                                                                                                                                                         3.9s
------
 > [linux/arm/v7 build 4/4] RUN dotnet restore:
#23 7.082 System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Cli.Parser' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
#23 7.082    at System.Collections.Generic.SparseArrayBuilder`1.Reserve(Int32 count)
#23 7.085    at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
#23 7.085    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
#23 7.085    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
#23 7.085    at Microsoft.DotNet.Cli.CommandLine.Accept.ZeroOrMoreOf(Option[] options)
#23 7.086    at Microsoft.DotNet.Cli.CommandLine.Option..ctor(String[] aliases, String help, ArgumentsRule arguments, Option[] options)
#23 7.086    at Microsoft.DotNet.Cli.CommandLine.Command..ctor(String name, String help, Option[] options, ArgumentsRule arguments, Boolean treatUnmatchedTokensAsErrors)
#23 7.086    at Microsoft.TemplateEngine.Cli.CommandParsing.CommandParserSupport.GetNewCommand(String commandName, Option[][] args)
#23 7.086    at Microsoft.TemplateEngine.Cli.CommandParsing.CommandParserSupport.CreateNewCommandWithoutTemplateInfo(String commandName)
#23 7.086    at Microsoft.DotNet.Cli.Parser..cctor()
#23 7.086    --- End of inner exception stack trace ---
#23 7.086    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
#23 7.086    at Microsoft.DotNet.Cli.Program.Main(String[] args)
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c dotnet restore]: buildkit-runc did not terminate successfully
```

I'm no expert in dotnet programming so I'm stuck. Probably @bluewalk can shed some light in here.

**Comment by bluewalk** [comment]
Hi, this is an issue with the dotnet command.
As the dockerfile is using the amd64 image I think a separate Dockerfile needs to be created using one of the arm32 images from microsoft. I haven't yet tried this though so currently I'm just guessing.

**Comment by Zerwin** [comment]
I didn't find a solution for multi-arch as I really don't know my way around that, but an easy solution for now if you already have an arm computer, is to change the base images in the dockerfile to arm ones provided by microsoft.

Something I can confirm to work is:
Replace 
```FROM mcr.microsoft.com/dotnet/runtime:5.0-alpine```
with 
`FROM mcr.microsoft.com/dotnet/runtime:5.0-buster-slim-arm32v7`

in both build and runtime. So my Dockerfile looked like this:

```
FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm32v7 AS build
WORKDIR /app

COPY . ./
RUN dotnet restore

# STAGE02 - Publish the application
FROM build AS publish
WORKDIR /app/Net.Bluewalk.NukiBridge2Mqtt.Console
RUN dotnet publish -c Release -o ../out
RUN rm ../out/*.pdb

# STAGE03 - Create the final image 
FROM mcr.microsoft.com/dotnet/runtime:5.0-buster-slim-arm32v7 AS runtime
WORKDIR /app
COPY --from=publish /app/out ./

ENTRYPOINT ["dotnet", "Net.Bluewalk.NukiBridge2Mqtt.Console.dll", "docker"]
```

Now just run `docker build -t nukibridge ./` on the arm device itself and it will build the image.

**Comment by bluewalk** [comment]
Hi that's great to hear!

I will try to create multi-arch images when I have time using buildx so that future updates will also work on the Raspberry Pi

**Comment by bluewalk** [comment]
Hi @Zerwin  and @jk I have just published multi-arch images.
I am curious if these work on your devices, I you have the time, could you give it a shot? :)

**Comment by jk** [comment]
Hi @bluewalk 

I already build my own solution in the meantime with ReachtPHP and RabbitMQ, but perhaps I give it a shot when I find the time. Thanks anyway.

**Comment by bluewalk** [comment]
Closing this issue, it of course can be reopened if there are other questions regarding the RPi images
